// Regenerates world.js: country borders + coastlines for the globe, as flat [lon, lat, ...] polylines.
// Source: Natural Earth via the world-atlas package (public domain). Run: npm run build:world
import { readFileSync, writeFileSync } from "node:fs";
import { mesh } from "topojson-client";

const res = process.argv[2] ?? "110m";
const topo = JSON.parse(readFileSync(new URL(`../node_modules/world-atlas/countries-${res}.json`, import.meta.url)));
// mesh() merges shared borders so each edge is drawn once
const lines = mesh(topo, topo.objects.countries).coordinates.map((line) =>
  line.flatMap(([lon, lat]) => [Math.round(lon * 10) / 10, Math.round(lat * 10) / 10]),
);
const points = lines.reduce((n, l) => n + l.length / 2, 0);
writeFileSync(
  new URL("../world.js", import.meta.url),
  `// Generated by scripts/build-world.mjs from Natural Earth ${res} (public domain). Do not edit.\n` +
    `// ${lines.length} polylines, ${points} points, each flat [lon, lat, lon, lat, ...].\n` +
    `export default ${JSON.stringify(lines)};\n`,
);
console.log(`world.js: ${lines.length} lines, ${points} points`);
